#드라이브 마운트 및 필요 라이브러리 로드

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/최종프로젝트

/content/drive/MyDrive/Colab Notebooks/프로그래머스/최종프로젝트

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

#데이터 로딩, 결측치 및 기초 통계량 확인

In [ ]:
train = pd.read_csv("./dataset/train.csv")
test = pd.read_csv("./dataset/test.csv")

In [ ]:
print(train.shape)
print(test.shape)

(3489, 18)
(3489, 17)

##trian head, describe, info

In [ ]:
train.head()

,id,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,Designation,MonthlyIncome,customer_info,ProdTaken
0,0,50歳,Self Enquiry,2,900秒,Large Business,male,1.0,4.0,Basic,3.0,5,1,4,Executive,253905.0,未婚 車未所持 子供なし,1
1,1,56歳,Company Invited,1,14分,Salaried,Male,1.0,4.0,Standard,3.0,2,1,4,Senior Manager,404475.0,"離婚済み,車あり,子供無し",0
2,2,NaN,Self Enquiry,1,10分,Large Business,Female,1.0,3.0,Basic,3.0,4,0,4,Executive,278145.0,"結婚済み、自動車未所有,子供なし",1
3,3,三十七歳,Self Enquiry,2,1080秒,Small Business,female,1.0,3.0,Standard,4.0,1,0,5,Senior Manager,326805.0,離婚済み、車所持、子供無し,0
4,4,48歳,Company Invited,3,1020秒,Small Business,female,1.0,3.0,Basic,4.0,4,0,4,Executive,258435.0,独身／車所持／無子,1

In [ ]:
train.describe()

,id,CityTier,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,Passport,PitchSatisfactionScore,ProdTaken
count,3489.000000,3489.000000,3489.000000,3456.000000,3489.000000,3489.000000,3489.000000,3489.000000
mean,1744.000000,1.697048,2.394669,7.765336,3.441101,0.102608,2.513901,0.142448
std,1007.331872,0.671500,0.726612,39.498670,0.599633,0.303490,1.115412,0.349559
min,0.000000,1.000000,1.000000,1.000000,3.000000,0.000000,1.000000,0.000000
25%,872.000000,1.000000,2.000000,3.000000,3.000000,0.000000,2.000000,0.000000
50%,1744.000000,2.000000,2.000000,4.000000,3.000000,0.000000,2.000000,0.000000
75%,2616.000000,2.000000,3.000000,4.000000,4.000000,0.000000,3.000000,0.000000
max,3488.000000,3.000000,4.000000,600.000000,5.000000,1.000000,5.000000,1.000000

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3489 entries, 0 to 3488
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      3489 non-null   int64
 1   Age                     3389 non-null   object
 2   TypeofContact           3483 non-null   object
 3   CityTier                3489 non-null   int64
 4   DurationOfPitch         3368 non-null   object
 5   Occupation              3489 non-null   object
 6   Gender                  3489 non-null   object
 7   NumberOfPersonVisiting  3489 non-null   float64
 8   NumberOfFollowups       3456 non-null   float64
 9   ProductPitched          3489 non-null   object
 10  PreferredPropertyStar   3489 non-null   float64
 11  NumberOfTrips           3467 non-null   object
 12  Passport                3489 non-null   int64
 13  PitchSatisfactionScore  3489 non-null   int64
 14  Designation             3489 non-null   object
 15  MonthlyIncome           3433 non-null   object
 16  customer_info           3489 non-null   object
 17  ProdTaken               3489 non-null   int64
dtypes: float64(3), int64(5), object(10)
memory usage: 490.8+ KB

##test head, describe, info

In [ ]:
test.head()

,id,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,Designation,MonthlyIncome,customer_info
0,3489,４８歳,Self Enquiry,2,13分,Small Business,Male,1.0,4.0,Super De|uxe,3.0,7,0,3,AVP,496950.0,結婚済み 車所持 子供なし
1,3490,30代,Self Enquiry,2,12分,Small Business,Ｆｅｍａｌｅ,1.0,4.0,Standard,3.0,4,1,3,Senior Manager,月収30.0万円,結婚済み、車未所持、子供なし
2,3491,25歳,Self Enquiry,1,540秒,Salaried,Female,1.0,4.0,Basic,3.0,1,0,3,Executive,月収26.0万円,離婚済み、自動車未所有、子供なし
3,3492,21歳,Company Invited,2,420秒,Salaried,Male,1.0,4.0,Basic,4.0,1,0,3,Senior Manager,259875.0,離婚済み、自動車所有、子供なし
4,3493,41歳,Company Invited,1,7分,Salaried,MALE,1.0,4.0,Basic,3.0,1,0,4,Executive,268830.0,独身/車所持／子供なし

In [ ]:
test.describe()

,id,CityTier,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,Passport,PitchSatisfactionScore
count,3489.000000,3489.000000,3489.000000,3465.000000,3489.000000,3489.000000,3489.000000
mean,5233.000000,1.682717,2.407567,6.849639,3.431929,0.095156,2.500143
std,1007.331872,0.671710,0.741628,34.890230,0.599618,0.293473,1.153904
min,3489.000000,1.000000,1.000000,1.000000,3.000000,0.000000,1.000000
25%,4361.000000,1.000000,2.000000,3.000000,3.000000,0.000000,2.000000
50%,5233.000000,2.000000,2.000000,4.000000,3.000000,0.000000,2.000000
75%,6105.000000,2.000000,3.000000,4.000000,4.000000,0.000000,3.000000
max,6977.000000,3.000000,4.000000,500.000000,5.000000,1.000000,5.000000

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3489 entries, 0 to 3488
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      3489 non-null   int64
 1   Age                     3396 non-null   object
 2   TypeofContact           3477 non-null   object
 3   CityTier                3489 non-null   int64
 4   DurationOfPitch         3358 non-null   object
 5   Occupation              3489 non-null   object
 6   Gender                  3489 non-null   object
 7   NumberOfPersonVisiting  3489 non-null   float64
 8   NumberOfFollowups       3465 non-null   float64
 9   ProductPitched          3489 non-null   object
 10  PreferredPropertyStar   3489 non-null   float64
 11  NumberOfTrips           3447 non-null   object
 12  Passport                3489 non-null   int64
 13  PitchSatisfactionScore  3489 non-null   int64
 14  Designation             3489 non-null   object
 15  MonthlyIncome           3440 non-null   object
 16  customer_info           3489 non-null   object
dtypes: float64(3), int64(4), object(10)
memory usage: 463.5+ KB

## 결측값 확인

In [ ]:
train_null = train.isnull().sum()
test_null = test.isnull().sum()
null_df = pd.concat([train_null, test_null], axis=1)
null_df.columns = ['Train Nulls', 'Test Nulls']
null_df

                        Train Nulls  Test Nulls
id                                0         0.0
Age                             100        93.0
TypeofContact                     6        12.0
CityTier                          0         0.0
DurationOfPitch                 121       131.0
Occupation                        0         0.0
Gender                            0         0.0
NumberOfPersonVisiting            0         0.0
NumberOfFollowups                33        24.0
ProductPitched                    0         0.0
PreferredPropertyStar             0         0.0
NumberOfTrips                    22        42.0
Passport                          0         0.0
PitchSatisfactionScore            0         0.0
Designation                       0         0.0
MonthlyIncome                    56        49.0
customer_info                     0         0.0
ProdTaken                         0         NaN

#Age 전처리

In [ ]:
def extract_age(text):
  pattern = r'\d+'

  kanji_to_arabic = {
      '一': 1, '二': 2, '三': 3, '四': 4, '五': 5,
      '六': 6, '七': 7, '八': 8, '九': 9, '十': 10
  }

  match = re.search(pattern, text)
  if match:
      return int(match.group())
  else:
      numeric_age = 0
      chars = list(text)
      i = 0
      while i < len(chars):
          char = chars[i]
          if char in kanji_to_arabic:
              if char == '十':
                  if i == 0:
                      numeric_age += 10
                  else:
                      numeric_age += kanji_to_arabic[char]
              else:
                  numeric_age += kanji_to_arabic[char]
          i += 1
      return numeric_age

train['Age'] = train['Age'].apply(lambda age_text: extract_age(age_text) if isinstance(age_text, str) and age_text else None)
test['Age'] = test['Age'].apply(lambda age_text: extract_age(age_text) if isinstance(age_text, str) and age_text else None)

In [ ]:
test['Age'].describe()

count    3396.000000
mean       37.760306
std        10.725919
min        10.000000
25%        30.000000
50%        37.000000
75%        46.000000
max        61.000000
Name: Age, dtype: float64

In [ ]:
train['Age'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 3489 entries, 0 to 3488
Series name: Age
Non-Null Count  Dtype
--------------  -----
3389 non-null   float64
dtypes: float64(1)
memory usage: 27.4 KB

In [ ]:
test['Age'].describe()

count    3396.000000
mean       37.760306
std        10.725919
min        10.000000
25%        30.000000
50%        37.000000
75%        46.000000
max        61.000000
Name: Age, dtype: float64

#DurationOfPitch 전처리

In [ ]:
def convert_duration(item):
    if isinstance(item, str) and item:
        total_seconds = 0
        if '分' in item:
            minutes = int(item.replace('分', ''))
            total_seconds += minutes * 60  # 분을 초로 변환
        if '秒' in item:
            seconds = int(item.replace('秒', ''))
            total_seconds += seconds  # 이미 초이므로 그대로 더함
        return total_seconds
    return pd.NA

train['DurationOfPitch'] = train['DurationOfPitch'].apply(convert_duration)
test['DurationOfPitch'] = test['DurationOfPitch'].apply(convert_duration)

In [ ]:
train['DurationOfPitch'].head()

0     900
1     840
2     600
3    1080
4    1020
Name: DurationOfPitch, dtype: object

In [ ]:
train['DurationOfPitch'].describe()

count     3368
unique      33
top        480
freq       338
Name: DurationOfPitch, dtype: int64

# Gender 전처리

In [ ]:
import unicodedata

# Gender 속성 변형
def normalize_Str(gender):
    if isinstance(gender, str):
        normalized = unicodedata.normalize('NFKC', gender).lower().strip()  # 공백 제거
        return normalized.replace(" ", "")  # 모든 공백 제거
    return gender

In [ ]:
train['Gender'] = train['Gender'].apply(normalize_Str)
test['Gender'] = test['Gender'].apply(normalize_Str)

In [ ]:
print(train['Gender'].unique())
print(test['Gender'].unique())

['male' 'female']
['male' 'female']

#Product Pitched 전처리

In [ ]:
pp_unique = train['ProductPitched'].unique()
pp_unique

array(['Basic', 'Standard', 'Super Deluxe', 'basic', 'SUPER DELUXE',
       'super deluxe', 'BASIC', 'Deluxe', 'deluxe', 'STANᗞARD',
       'STANDARD', 'Вasic', 'DELUXE', 'ꓢuper De|uxe', 'Ѕuper Deluxe',
       'BAՏIC', 'Basıc', 'King', 'Super De|uxe', 'king', 'standard',
       'KING', 'BΑSIC', 'B𝖺sic', 'De|uxe', 'ᎠELUXE', 'Basiϲ', 'de|u×e',
       'Delu×e', 'Standar𝔡', 'Basi𝘤', 'Βasic', 'Տuper Deluxe', 'Staոdard',
       'BAꓢIC', 'ᗞeluxe', 'Տtandard', 'Βası𝘤', 'Kıng', 'Baｓic', 'basıc',
       'super de|uxe', 'Stand𝖺rd', 'S𝘵andard', '𐊡asic', 'St𝖺ndard',
       'Super ᗞeluxe', 'de|uxe', 'ｓuper deluxe', 'STANDARᎠ', 'Basiс',
       'DΕLUXΕ', 'ꓢuper Deluxe', 'BASΙC', 'ꓢtandard', 'В𝖺sic', 'Standa𝘳d',
       'basiϲ', 'staոdard', 'Super Ꭰeluxe', 'DELUXΕ', 'Ѕtandard', '𐊡asi𝘤',
       'Ꭰeluxe', 'Kıոg', '𝙳eluxe', 'Kiոg', 'Βasıc', 'BASIС',
       'SUPER DΕLUXE', 'B𝖺si𝘤', 'ΒASIС', 'Super 𝙳eluxe', 'Տtanda𝘳d',
       'Basıϲ', 'ЅTANDARD'], dtype=object)

In [ ]:
!pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.9.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.9.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 22.7 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.9.6

In [ ]:
# 필요한 라이브러리 가져오기
from rapidfuzz import process, fuzz
import pandas as pd
import unicodedata
import re

# 전처리 함수 정의
def preprocess_text(text):
    text = unicodedata.normalize('NFKC', text)
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

# 퍼지 매칭 함수 정의
def fuzzy_category_mapping(text, choices, scorer=fuzz.WRatio):
    match = process.extractOne(text, choices, scorer=scorer)
    if match:
        return choices[match[2]]

# 카테고리 매핑
category_mapping = ['basic', 'standard', 'deluxe', 'super deluxe', 'king']

# 데이터 전처리 및 카테고리 할당
train['ProductPitched'] = train['ProductPitched'].apply(preprocess_text)
train['ProductPitched'] = train['ProductPitched'].apply(
    fuzzy_category_mapping, choices=category_mapping)

# 데이터 전처리 및 카테고리 할당
test['ProductPitched'] = test['ProductPitched'].apply(preprocess_text)
test['ProductPitched'] = test['ProductPitched'].apply(
    fuzzy_category_mapping, choices=category_mapping)

# 결과 출력
print(train['ProductPitched'])

0          basic
1       standard
2          basic
3       standard
4          basic
          ...
3484       basic
3485       basic
3486    standard
3487        king
3488       basic
Name: ProductPitched, Length: 3489, dtype: object

In [ ]:
print(train['ProductPitched'].unique())
print(test['ProductPitched'].unique())

['basic' 'standard' 'super deluxe' 'deluxe' 'king']
['super deluxe' 'standard' 'basic' 'deluxe' 'king']

#NumberOfTrips 전처리

In [ ]:
# NumberOfTrips 속성 변형 함수
def extract_number_of_trips(trips):
    if isinstance(trips, str):
        match = re.search(r'\d+', trips)  # 숫자 추출
        if match:
            return int(match.group())  # 숫자를 정수로 변환하여 반환
    return trips  # 숫자가 없으면 원래 값 반환

train['NumberOfTrips'] = train['NumberOfTrips'].apply(lambda trips: 2 if trips == '半年に1回' else trips)
train['NumberOfTrips'] = train['NumberOfTrips'].apply(lambda trips: 1 if trips == '四半期に1回' else trips)
train['NumberOfTrips'] = train['NumberOfTrips'].apply(extract_number_of_trips)

test['NumberOfTrips'] = test['NumberOfTrips'].apply(lambda trips: 2 if trips == '半年に1回' else trips)
test['NumberOfTrips'] = test['NumberOfTrips'].apply(lambda trips: 1 if trips == '四半期に1回' else trips)
test['NumberOfTrips'] = test['NumberOfTrips'].apply(extract_number_of_trips)

In [ ]:
train['NumberOfTrips'].describe()

count    3467.000000
mean        3.192097
std         1.733887
min         1.000000
25%         2.000000
50%         3.000000
75%         5.000000
max         8.000000
Name: NumberOfTrips, dtype: float64

In [ ]:
train['NumberOfTrips'].unique()

array([ 5.,  2.,  4.,  1.,  6.,  3.,  7.,  8., nan])

#Desgination 전처리

In [ ]:
d_unique = train['Designation'].unique()
d_unique

array(['Executive', 'Senior Manager', 'AVP', 'Manager', 'Senior Manage𝙧',
       'Execuｔive', 'Μanager', 'VP', 'Sеnior Manager', 'ΑVP', 'АVP',
       'E×ecutive', 'Mαnage𝙧', 'Executiѵе', 'Ѕenior Manager', 'Managеr',
       'Еxecutivе', 'Senior Μanαger', 'Еxecuｔive', 'Exеcutivе',
       'Exеcutive', 'Senior Managе𝙧', 'Manage𝙧', 'Senio𝙧 Manager',
       'Manαger', 'Μanage𝙧', 'Manαgеr', 'Senior Managеr', 'Executivе',
       'Executiѵe', 'Е×еcutive', 'Еxecutive', 'VＰ', 'Տenior Μanager',
       'Exеcutiѵе', 'Senior Manαger', 'Mαnager', 'Senior Mαnαger',
       'E×еcutiѵe', 'Ѕenior Manαger', 'Exеcｕtive', 'Execｕtive', 'Mαnαger',
       'Μanagеr', 'E×ecｕtive', 'Sеnior Managеr', 'Տenior Manager', 'AVＰ',
       'Exеcｕtivе', 'Mαnagеr', 'Еxеcutivе', 'Senior Mαnager', 'Е×ecutive'],
      dtype=object)

In [ ]:
# 필요한 라이브러리 가져오기
from rapidfuzz import process, fuzz
import pandas as pd
import unicodedata
import re

# 전처리 함수 정의
def preprocess_text(text):
    text = unicodedata.normalize('NFKC', text)
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

# 퍼지 매칭 함수 정의
def fuzzy_category_mapping(text, choices, scorer=fuzz.WRatio):
    match = process.extractOne(text, choices, scorer=scorer)
    if match:
        return choices[match[2]]

# 카테고리 매핑
category_mapping = ['avp','vp','executive','senior manager','manager']

# 데이터 전처리 및 카테고리 할당
train['Designation'] = train['Designation'].apply(preprocess_text)
train['Designation'] = train['Designation'].apply(
    fuzzy_category_mapping, choices=category_mapping)

# 데이터 전처리 및 카테고리 할당
test['Designation'] = test['Designation'].apply(preprocess_text)
test['Designation'] = test['Designation'].apply(
    fuzzy_category_mapping, choices=category_mapping)

# 결과 출력
print(train['Designation'])

0            executive
1       senior manager
2            executive
3       senior manager
4            executive
             ...
3484         executive
3485         executive
3486    senior manager
3487                vp
3488         executive
Name: Designation, Length: 3489, dtype: object

In [ ]:
print(train['Designation'].unique())
print(test['Designation'].unique())

['executive' 'senior manager' 'avp' 'manager' 'vp']
['avp' 'senior manager' 'executive' 'manager' 'vp']

#MonthlyIncome 전처리

In [ ]:
def convert_monthly_income(income):

    #문자열에서 '月収'와 '万円' 포함된 데이터 처리
    if isinstance(income, str):
        match = re.search(r'(\d+(\.\d+)?)', income)
        if '月収' in income or '万円' in income:
        # 정규 표현식으로 숫자 추출
          if match:
              # 숫자 변환 및 만엔 단위 변환
              return float(match.group(0)) * 10000  # 만엔을 원으로 변환
        else:
          return float(match.group(0))
    return pd.NA  # 위 조건에 맞지 않는 경우 NaN 반환

train['MonthlyIncome'] = train['MonthlyIncome'].apply(convert_monthly_income)
test['MonthlyIncome'] = test['MonthlyIncome'].apply(convert_monthly_income)

In [ ]:
train[['MonthlyIncome']].head(20)

   MonthlyIncome
0       253905.0
1       404475.0
2       278145.0
3       326805.0
4       258435.0
5       260000.0
6       453180.0
7       261900.0
8       247800.0
9       257610.0
10      351900.0
11      416430.0
12      477555.0
13      440000.0
14      300000.0
15      253665.0
16      258600.0
17      500000.0
18      400000.0
19      286245.0

In [ ]:
train.describe()

,id,Age,CityTier,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,ProdTaken
count,3489.000000,3389.000000,3489.000000,3489.000000,3456.000000,3489.000000,3467.000000,3489.000000,3489.000000,3489.000000
mean,1744.000000,37.976394,1.697048,2.394669,7.765336,3.441101,3.192097,0.102608,2.513901,0.142448
std,1007.331872,10.673292,0.671500,0.726612,39.498670,0.599633,1.733887,0.303490,1.115412,0.349559
min,0.000000,10.000000,1.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000
25%,872.000000,30.000000,1.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000
50%,1744.000000,38.000000,2.000000,2.000000,4.000000,3.000000,3.000000,0.000000,2.000000,0.000000
75%,2616.000000,46.000000,2.000000,3.000000,4.000000,4.000000,5.000000,0.000000,3.000000,0.000000
max,3488.000000,61.000000,3.000000,4.000000,600.000000,5.000000,8.000000,1.000000,5.000000,1.000000

#customer_info 전처리
* 구분자로 먼저 차량 보유 여부, 혼인 여부, 아이 동반 여부 컬럼 나누기

In [ ]:
import pandas as pd
import re

# 문자열을 구분자로 나누어 새로운 컬럼으로 생성하는 함수 정의
def split_customer_info(info):
    info = re.sub(r'[^\w\s、/]', ' ', info)  # 특수 문자 공백처리
    info = re.sub(r'[\t\n、/]', ' ', info)  # 탭과 줄 바꿈 문자 공백 처리
    info = re.sub(r'\s+', ' ', info)  # 다중 공백을 단일 공백으로 변환

    # 정보 분리
    parts = re.split(' ', info)  # 공백 기호로 분리
    parts = [part.strip() for part in parts]  # 각 부분의 양쪽 공백 제거

    # 기본값 설정
    while len(parts) < 3:  # 필요한 만큼의 컬럼 수에 맞추기
        parts.append('Unknown')

    return pd.Series(parts[:3], index=['Marital_Status', 'Car_Ownership', 'Has_Children'])

# 데이터프레임에 적용
train[['Marital_Status', 'Car_Ownership', 'Has_Children']] = train['customer_info'].apply(split_customer_info)
test[['Marital_Status', 'Car_Ownership', 'Has_Children']] = train['customer_info'].apply(split_customer_info)

# 결과 확인
train[['Marital_Status', 'Car_Ownership', 'Has_Children']]

     Marital_Status Car_Ownership Has_Children
0                未婚          車未所持         子供なし
1              離婚済み           車あり         子供無し
2              結婚済み        自動車未所有         子供なし
3              離婚済み           車所持         子供無し
4                独身           車所持           無子
...             ...           ...          ...
3484           離婚済み         乗用車所持         子供なし
3485           結婚済み           車所持         子供2人
3486             独身           車所持        こども1人
3487           結婚済み        自動車未所有         子供2人
3488           結婚済み          車未所持         子供1人

[3489 rows x 3 columns]

In [ ]:
print(train['Marital_Status'].unique())
print(test['Marital_Status'].unique())

['未婚' '離婚済み' '結婚済み' '独身']
['未婚' '離婚済み' '結婚済み' '独身']

In [ ]:
print(train['Car_Ownership'].unique())
print(test['Car_Ownership'].unique())

['車未所持' '車あり' '自動車未所有' '車所持' '自家用車あり' '車保有' '車保有なし' '乗用車所持' '乗用車なし'
 '自動車所有' '自家用車なし' '車なし']
['車未所持' '車あり' '自動車未所有' '車所持' '自家用車あり' '車保有' '車保有なし' '乗用車所持' '乗用車なし'
 '自動車所有' '自家用車なし' '車なし']

In [ ]:
print(train['Has_Children'].unique())
print(test['Has_Children'].unique())

['子供なし' '子供無し' '無子' '子供ゼロ' '非育児家庭' '子育て状況不明' '子の数不詳' '子供の数不明' 'こども1人' '1児'
 '子供1人' '子供有り' 'わからない' 'こども2人' '子供2人' 'こども3人' '子供3人' '不明' '2児' '3児']
['子供なし' '子供無し' '無子' '子供ゼロ' '非育児家庭' '子育て状況不明' '子の数不詳' '子供の数不明' 'こども1人' '1児'
 '子供1人' '子供有り' 'わからない' 'こども2人' '子供2人' 'こども3人' '子供3人' '不明' '2児' '3児']

In [ ]:
marital_status_map = {
    '未婚': 'unmarried',
    '離婚済み': 'divorced',
    '結婚済み': 'married',
    '独身': 'single'
}

In [ ]:
car_ownership_map = {
    '車未所持': '0',
    '車あり': '1',
    '自動車未所有': '0',
    '車所持': '1',
    '自家用車あり': '1',
    '車保有': '1',
    '車保有なし': '0',
    '乗用車所持': '1',
    '乗用車なし': '0',
    '自動車所有': '1',
    '自家用車なし': '0',
    '車なし': '0'
}

In [ ]:
has_children_map = {
    '子供なし': '0',
    '子供無し': '0',
    '無子': '0',
    '子供ゼロ': '0',
    '非育児家庭': '0',
    '子育て状況不明': '0',
    '子の数不詳': '0',
    '子供の数不明': '0',
    'こども1人': '1',
    '1児': '1',
    '子供1人': '1',
    '子供有り(1人)': '1',
    'わからない': '0',
    '子供有り': '1',
    'こども2人': '1',
    '子供2人': '1',
    '子供有り(2人)': '1',
    'こども3人': '1',
    '子供3人': '1',
    '不明': '0',
    '2児': '1',
    '3児': '1',
    '子供有り(3人)': '1'
}

In [ ]:
train['Marital_Status'] = train['Marital_Status'].map(marital_status_map)
train['Car_Ownership'] = train['Car_Ownership'].map(car_ownership_map)
train['Has_Children'] = train['Has_Children'].map(has_children_map)

test['Marital_Status'] = test['Marital_Status'].map(marital_status_map)
test['Car_Ownership'] = test['Car_Ownership'].map(car_ownership_map)
test['Has_Children'] = test['Has_Children'].map(has_children_map)

#전처리 데이터셋 저장
#각 컬럼별 dtype object에서 수정 필요

In [ ]:
train.drop(['customer_info','id'],axis=1,inplace=True)
test.drop(['customer_info'],axis=1,inplace=True)

In [ ]:
print(train.dtypes)
print(test.dtypes)

Age                       float64
TypeofContact              object
CityTier                    int64
DurationOfPitch            object
Occupation                 object
Gender                     object
NumberOfPersonVisiting    float64
NumberOfFollowups         float64
ProductPitched             object
PreferredPropertyStar     float64
NumberOfTrips             float64
Passport                    int64
PitchSatisfactionScore      int64
Designation                object
MonthlyIncome              object
ProdTaken                   int64
Marital_Status             object
Car_Ownership              object
Has_Children               object
dtype: object
id                          int64
Age                       float64
TypeofContact              object
CityTier                    int64
DurationOfPitch            object
Occupation                 object
Gender                     object
NumberOfPersonVisiting    float64
NumberOfFollowups         float64
ProductPitched             object
PreferredPropertyStar     float64
NumberOfTrips             float64
Passport                    int64
PitchSatisfactionScore      int64
Designation                object
MonthlyIncome              object
Marital_Status             object
Car_Ownership              object
Has_Children               object
dtype: object

In [ ]:
# dtype을 수정하는 함수
def adjust_dtypes(df):
    # MonthlyIncome 컬럼을 float로 변환
    df['MonthlyIncome'] = pd.to_numeric(df['MonthlyIncome'], errors='coerce')
    df['DurationOfPitch'] = pd.to_numeric(df['DurationOfPitch'], errors='coerce')

    # Object 타입 중 범주형 데이터를 category 타입으로 변환
    category_columns = ['TypeofContact', 'Occupation', 'Gender',
                        'ProductPitched', 'Designation',
                        'Marital_Status']

    for col in category_columns:
        df[col] = df[col].astype('category')

    # NumberOfPersonVisiting, NumberOfFollowups, PreferredPropertyStar, NumberOfTrips 컬럼을 float로 변환
    df['NumberOfPersonVisiting'] = df['NumberOfPersonVisiting'].astype(float)
    df['NumberOfFollowups'] = df['NumberOfFollowups'].astype(float)
    df['PreferredPropertyStar'] = df['PreferredPropertyStar'].astype(float)
    df['NumberOfTrips'] = df['NumberOfTrips'].astype(float)
    df[['Car_Ownership', 'Has_Children']] = df[['Car_Ownership', 'Has_Children']].astype(int)

    return df

# dtype을 수정한 데이터프레임
train = adjust_dtypes(train)
test = adjust_dtypes(test)
# 결과 확인
print(train.dtypes)
print(test.dtypes)

Age                        float64
TypeofContact             category
CityTier                     int64
DurationOfPitch            float64
Occupation                category
Gender                    category
NumberOfPersonVisiting     float64
NumberOfFollowups          float64
ProductPitched            category
PreferredPropertyStar      float64
NumberOfTrips              float64
Passport                     int64
PitchSatisfactionScore       int64
Designation               category
MonthlyIncome              float64
ProdTaken                    int64
Marital_Status            category
Car_Ownership                int64
Has_Children                 int64
dtype: object
id                           int64
Age                        float64
TypeofContact             category
CityTier                     int64
DurationOfPitch            float64
Occupation                category
Gender                    category
NumberOfPersonVisiting     float64
NumberOfFollowups          float64
ProductPitched            category
PreferredPropertyStar      float64
NumberOfTrips              float64
Passport                     int64
PitchSatisfactionScore       int64
Designation               category
MonthlyIncome              float64
Marital_Status            category
Car_Ownership                int64
Has_Children                 int64
dtype: object

In [ ]:
train

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,Designation,MonthlyIncome,ProdTaken,Marital_Status,Car_Ownership,Has_Children
0,50.0,Self Enquiry,2,900.0,Large Business,male,1.0,4.0,basic,3.0,5.0,1,4,executive,253905.0,1,unmarried,0,0
1,56.0,Company Invited,1,840.0,Salaried,male,1.0,4.0,standard,3.0,2.0,1,4,senior manager,404475.0,0,divorced,1,0
2,NaN,Self Enquiry,1,600.0,Large Business,female,1.0,3.0,basic,3.0,4.0,0,4,executive,278145.0,1,married,0,0
3,20.0,Self Enquiry,2,1080.0,Small Business,female,1.0,3.0,standard,4.0,1.0,0,5,senior manager,326805.0,0,divorced,1,0
4,48.0,Company Invited,3,1020.0,Small Business,female,1.0,3.0,basic,4.0,4.0,0,4,executive,258435.0,1,single,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3484,40.0,Self Enquiry,2,1560.0,Salaried,male,2.0,3.0,basic,3.0,3.0,0,1,executive,258900.0,1,divorced,1,0
3485,40.0,Self Enquiry,1,540.0,Large Business,male,3.0,3.0,basic,5.0,5.0,0,3,executive,260415.0,0,married,1,1
3486,31.0,Self Enquiry,1,840.0,Small Business,female,3.0,2.0,standard,3.0,5.0,0,4,senior manager,317340.0,0,single,1,1
3487,56.0,Company Invited,2,900.0,Salaried,male,3.0,6.0,king,3.0,7.0,1,4,vp,527910.0,1,married,0,1
3488,42.0,Self Enquiry,1,540.0,Small Business,male,3.0,1.0,basic,3.0,3.0,0,1,executive,278190.0,0,married,0,1

In [ ]:
test

,id,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,Designation,MonthlyIncome,Marital_Status,Car_Ownership,Has_Children
0,3489,48.0,Self Enquiry,2,780.0,Small Business,male,1.0,4.0,super deluxe,3.0,7.0,0,3,avp,496950.0,unmarried,0,0
1,3490,30.0,Self Enquiry,2,720.0,Small Business,female,1.0,4.0,standard,3.0,4.0,1,3,senior manager,300000.0,divorced,1,0
2,3491,25.0,Self Enquiry,1,540.0,Salaried,female,1.0,4.0,basic,3.0,1.0,0,3,executive,260000.0,married,0,0
3,3492,21.0,Company Invited,2,420.0,Salaried,male,1.0,4.0,basic,4.0,1.0,0,3,senior manager,259875.0,divorced,1,0
4,3493,41.0,Company Invited,1,420.0,Salaried,male,1.0,4.0,basic,3.0,1.0,0,4,executive,268830.0,single,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3484,6973,41.0,Company Invited,1,840.0,Small Business,female,1.0,3.0,basic,3.0,2.0,0,4,executive,261840.0,divorced,1,0
3485,6974,44.0,Company Invited,1,2100.0,Salaried,male,3.0,5.0,deluxe,3.0,3.0,0,3,manager,349770.0,married,1,1
3486,6975,24.0,Self Enquiry,2,1260.0,Small Business,male,2.0,3.0,basic,3.0,2.0,0,3,executive,270000.0,single,1,1
3487,6976,25.0,Self Enquiry,1,540.0,Small Business,male,2.0,3.0,basic,3.0,2.0,0,3,executive,272430.0,married,0,1
3488,6977,44.0,Self Enquiry,1,480.0,Small Business,female,4.0,4.0,deluxe,3.0,5.0,0,1,manager,411795.0,married,0,1

In [ ]:
train.to_csv('./preprocessed_train.csv', index=False)

In [ ]:
test.to_csv('./preprocessed_test.csv', index=False)